-- Initial scalar schema transcribed from the supplied Prisma contract.

-- Generated by scripts/materialize-initial-sql.mjs, NOT by the Prisma CLI.

-- Pending Prisma-engine diff verification; tested in embedded PostgreSQL.

-- UUIDs and @updatedAt values are supplied by application code, as in Prisma.

CREATE TYPE "Role" AS ENUM ('ORGANIZATION_ADMIN', 'MANAGER', 'BROKER');

CREATE TYPE "LeadState" AS ENUM ('NEW', 'CONTACTED', 'QUALIFYING', 'QUALIFIED', 'MATCHING', 'OPPORTUNITY', 'VISIT_REQUESTED', 'VISIT_SCHEDULED', 'VISIT_COMPLETED', 'NEGOTIATION', 'PROPOSAL', 'WON', 'PAUSED', 'NURTURE', 'RECOVERY', 'NO_FIT', 'LOST', 'DUPLICATE', 'BLOCKED');

CREATE TYPE "OperationType" AS ENUM ('SALE', 'RENT', 'UNKNOWN');

CREATE TYPE "FinancingStatus" AS ENUM ('APPROVED', 'OWN_FUNDS', 'DOWN_PAYMENT', 'UNDER_REVIEW', 'UNKNOWN', 'UNABLE');

CREATE TYPE "Fit" AS ENUM ('EXCELLENT', 'GOOD', 'LIMITED', 'NONE', 'UNKNOWN');

CREATE TYPE "LossReason" AS ENUM ('NO_RESPONSE', 'TIMING', 'FINANCING_PENDING', 'NO_INVENTORY', 'BOUGHT_ELSEWHERE', 'EXPLICIT_DISINTEREST', 'PRICE', 'OTHER', 'UNKNOWN');

CREATE TYPE "ActionType" AS ENUM ('CONTACT', 'FOLLOW_UP', 'QUALIFY', 'SCHEDULE_VISIT', 'ASK_FEEDBACK', 'RECOMMEND_PROPERTY', 'REACTIVATE', 'ESCALATE', 'WAIT', 'CLOSE');

CREATE TYPE "InterventionLevel" AS ENUM ('L0', 'L1', 'L2', 'L3', 'L4');

CREATE TYPE "RecommendationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'EXECUTED', 'DISMISSED', 'EXPIRED');

CREATE TYPE "ExceptionType" AS ENUM ('NEGOTIATION_REQUIRED', 'PRICE_REQUEST', 'PROPERTY_SWAP', 'COMPLAINT', 'DATA_CONFLICT', 'BROKER_UNAVAILABLE', 'HIGH_VALUE_LEAD_AT_RISK', 'UNKNOWN_INTENT', 'DUPLICATE', 'INTEGRATION_ERROR', 'DO_NOT_CONTACT');

CREATE TYPE "Severity" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

CREATE TYPE "ExceptionStatus" AS ENUM ('OPEN', 'ASSIGNED', 'RESOLVED', 'DISMISSED');

CREATE TYPE "ActorType" AS ENUM ('USER', 'API_KEY', 'IMPORT', 'SYSTEM');

CREATE TYPE "AnalysisMode" AS ENUM ('LIVE', 'HISTORICAL');

CREATE TYPE "JobStatus" AS ENUM ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED');

CREATE TYPE "ImportStatus" AS ENUM ('UPLOADED', 'VALIDATING', 'VALIDATED', 'IMPORTING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED');

CREATE TYPE "RowStatus" AS ENUM ('VALID', 'INVALID', 'WARNING', 'IMPORTED', 'SKIPPED');

CREATE TYPE "OutcomeType" AS ENUM ('REACTIVATED', 'VISIT', 'PROPOSAL', 'WON');

CREATE TYPE "JobType" AS ENUM ('ANALYZE', 'IMPORT_VALIDATE', 'IMPORT_COMMIT', 'AUDIT', 'PRIVACY_EXPORT', 'PRIVACY_ERASE', 'RETENTION');

CREATE TABLE "Organization" (
  "id" UUID NOT NULL,
  "name" VARCHAR(160) NOT NULL,
  "timezone" TEXT NOT NULL DEFAULT 'America/Sao_Paulo',
  "active" BOOLEAN NOT NULL DEFAULT true,
  "plan" TEXT NOT NULL DEFAULT 'PILOT',
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT "Organization_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "User" (
  "id" UUID NOT NULL,
  "authSubject" TEXT NOT NULL,
  "name" VARCHAR(160) NOT NULL,
  "email" VARCHAR(254) NOT NULL,
  "platformAdmin" BOOLEAN NOT NULL DEFAULT false,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "Membership" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "userId" UUID NOT NULL,
  "role" "Role" NOT NULL,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Membership_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "Broker" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "membershipId" UUID,
  "name" VARCHAR(160) NOT NULL,
  "email" VARCHAR(254),
  "phone" VARCHAR(20),
  "active" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT "Broker_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "PolicyVersion" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "version" INTEGER NOT NULL,
  "config" JSONB NOT NULL,
  "effectiveAt" TIMESTAMPTZ(3) NOT NULL,
  "createdBy" UUID NOT NULL,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PolicyVersion_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "Lead" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "source" VARCHAR(80) NOT NULL,
  "externalId" VARCHAR(160),
  "brokerId" UUID,
  "canonicalLeadId" UUID,
  "name" VARCHAR(160),
  "email" VARCHAR(254),
  "phone" VARCHAR(20),
  "sourceDetail" VARCHAR(200),
  "operationType" "OperationType" NOT NULL DEFAULT 'UNKNOWN',
  "propertyType" VARCHAR(80),
  "city" VARCHAR(120),
  "neighborhood" VARCHAR(120),
  "minPrice" DECIMAL(14,2),
  "maxPrice" DECIMAL(14,2),
  "availableDownPayment" DECIMAL(14,2),
  "bedrooms" INTEGER,
  "parkingSpaces" INTEGER,
  "financingStatus" "FinancingStatus" NOT NULL DEFAULT 'UNKNOWN',
  "purchaseTimelineDays" INTEGER,
  "motivation" VARCHAR(1000),
  "fit" "Fit" NOT NULL DEFAULT 'UNKNOWN',
  "currentState" "LeadState" NOT NULL DEFAULT 'NEW',
  "previousActiveState" "LeadState",
  "humanRequired" BOOLEAN NOT NULL DEFAULT false,
  "doNotContact" BOOLEAN NOT NULL DEFAULT false,
  "provisionalContactBlock" BOOLEAN NOT NULL DEFAULT false,
  "contactNotBefore" TIMESTAMPTZ(3),
  "resumeAt" TIMESTAMPTZ(3),
  "lossReason" "LossReason" NOT NULL DEFAULT 'UNKNOWN',
  "lostAt" TIMESTAMPTZ(3),
  "originalCreatedAt" TIMESTAMPTZ(3),
  "lastInteractionAt" TIMESTAMPTZ(3),
  "nextExpectedActionAt" TIMESTAMPTZ(3),
  "deadlineAt" TIMESTAMPTZ(3),
  "expectedActor" TEXT,
  "expectedAction" "ActionType",
  "nextCheckAt" TIMESTAMPTZ(3),
  "coverage" DECIMAL(4,3) NOT NULL DEFAULT 0,
  "sourceWatermark" TIMESTAMPTZ(3),
  "dataQuality" JSONB NOT NULL,
  "leadScore" INTEGER NOT NULL DEFAULT 8,
  "rescueRisk" INTEGER NOT NULL DEFAULT 0,
  "progressionScore" INTEGER NOT NULL DEFAULT 0,
  "rescuePriority" DECIMAL(5,2) NOT NULL DEFAULT 23.6,
  "queueEligible" BOOLEAN NOT NULL DEFAULT false,
  "suppressionReason" TEXT,
  "version" INTEGER NOT NULL DEFAULT 0,
  "projectionVersion" INTEGER NOT NULL DEFAULT 0,
  "deletedAt" TIMESTAMPTZ(3),
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT "Lead_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "LeadEvent" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "leadId" UUID NOT NULL,
  "type" VARCHAR(80) NOT NULL,
  "schemaVersion" INTEGER NOT NULL DEFAULT 1,
  "source" VARCHAR(80) NOT NULL,
  "sourceEventId" VARCHAR(200) NOT NULL,
  "sourceSequence" TEXT,
  "actorType" "ActorType" NOT NULL,
  "actorId" TEXT,
  "occurredAt" TIMESTAMPTZ(3) NOT NULL,
  "receivedAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "payload" JSONB NOT NULL,
  "isDerived" BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT "LeadEvent_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "AnalysisRun" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "leadId" UUID,
  "mode" "AnalysisMode" NOT NULL,
  "status" "JobStatus" NOT NULL DEFAULT 'PENDING',
  "asOf" TIMESTAMPTZ(3) NOT NULL,
  "knowledgeCutoff" TIMESTAMPTZ(3) NOT NULL,
  "from" TIMESTAMPTZ(3),
  "to" TIMESTAMPTZ(3),
  "inputVersion" INTEGER,
  "inputHash" TEXT NOT NULL,
  "policyVersion" INTEGER NOT NULL,
  "engineVersion" TEXT NOT NULL,
  "promptVersion" TEXT,
  "model" TEXT,
  "result" JSONB,
  "errorCode" TEXT,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completedAt" TIMESTAMPTZ(3),
  CONSTRAINT "AnalysisRun_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "StateHistory" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "leadId" UUID NOT NULL,
  "eventId" UUID NOT NULL,
  "analysisRunId" UUID NOT NULL,
  "previousState" "LeadState",
  "newState" "LeadState" NOT NULL,
  "changedAt" TIMESTAMPTZ(3) NOT NULL,
  "reason" TEXT NOT NULL,
  CONSTRAINT "StateHistory_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "ScoreSnapshot" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "leadId" UUID NOT NULL,
  "analysisRunId" UUID NOT NULL,
  "leadScore" INTEGER NOT NULL,
  "rescueRisk" INTEGER NOT NULL,
  "progressionScore" INTEGER NOT NULL,
  "rescuePriority" DECIMAL(5,2) NOT NULL,
  "coverage" DECIMAL(4,3) NOT NULL,
  "queueEligible" BOOLEAN NOT NULL,
  "suppressionReason" TEXT,
  "reasons" JSONB NOT NULL,
  "calculatedAt" TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT "ScoreSnapshot_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "Recommendation" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "leadId" UUID NOT NULL,
  "analysisRunId" UUID NOT NULL,
  "type" "ActionType" NOT NULL,
  "level" "InterventionLevel" NOT NULL,
  "priority" "Severity" NOT NULL,
  "status" "RecommendationStatus" NOT NULL DEFAULT 'PENDING',
  "title" VARCHAR(160) NOT NULL,
  "description" VARCHAR(1000) NOT NULL,
  "evidenceEventIds" JSONB NOT NULL,
  "confidence" DECIMAL(4,3) NOT NULL,
  "generatedBy" TEXT NOT NULL,
  "fingerprint" TEXT NOT NULL,
  "version" INTEGER NOT NULL DEFAULT 1,
  "decisionBy" UUID,
  "decisionReason" TEXT,
  "executedAt" TIMESTAMPTZ(3),
  "expiresAt" TIMESTAMPTZ(3) NOT NULL,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT "Recommendation_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "ExceptionCase" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "leadId" UUID,
  "type" "ExceptionType" NOT NULL,
  "severity" "Severity" NOT NULL,
  "status" "ExceptionStatus" NOT NULL DEFAULT 'OPEN',
  "assignedTo" UUID,
  "title" VARCHAR(160) NOT NULL,
  "description" VARCHAR(1000) NOT NULL,
  "evidenceEventIds" JSONB NOT NULL,
  "fingerprint" TEXT NOT NULL,
  "decisionReason" TEXT,
  "version" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "resolvedAt" TIMESTAMPTZ(3),
  CONSTRAINT "ExceptionCase_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "ImportBatch" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "createdBy" UUID NOT NULL,
  "source" TEXT NOT NULL,
  "objectKey" TEXT NOT NULL,
  "fileHash" TEXT NOT NULL,
  "dedupeKey" VARCHAR(200) NOT NULL,
  "status" "ImportStatus" NOT NULL DEFAULT 'UPLOADED',
  "mapping" JSONB NOT NULL,
  "mappingVersion" INTEGER NOT NULL DEFAULT 1,
  "counters" JSONB NOT NULL,
  "confirmedAt" TIMESTAMPTZ(3),
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expiresAt" TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT "ImportBatch_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "ImportRow" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "batchId" UUID NOT NULL,
  "rowNumber" INTEGER NOT NULL,
  "status" "RowStatus" NOT NULL,
  "normalized" JSONB,
  "errors" JSONB NOT NULL,
  "leadId" UUID,
  CONSTRAINT "ImportRow_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "OutboxJob" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "type" "JobType" NOT NULL,
  "status" "JobStatus" NOT NULL DEFAULT 'PENDING',
  "dedupeKey" TEXT NOT NULL,
  "payload" JSONB NOT NULL,
  "attempts" INTEGER NOT NULL DEFAULT 0,
  "availableAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "leaseUntil" TIMESTAMPTZ(3),
  "leaseOwner" TEXT,
  "progress" JSONB,
  "errorCode" TEXT,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completedAt" TIMESTAMPTZ(3),
  CONSTRAINT "OutboxJob_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "ApiKey" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "name" TEXT NOT NULL,
  "prefix" TEXT NOT NULL,
  "secretHash" TEXT NOT NULL,
  "scopes" TEXT[] NOT NULL,
  "expiresAt" TIMESTAMPTZ(3) NOT NULL,
  "revokedAt" TIMESTAMPTZ(3),
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "ApiKey_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "IdempotencyRecord" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "principal" TEXT NOT NULL,
  "method" TEXT NOT NULL,
  "path" TEXT NOT NULL,
  "key" TEXT NOT NULL,
  "requestHash" TEXT NOT NULL,
  "responseStatus" INTEGER NOT NULL,
  "response" JSONB NOT NULL,
  "expiresAt" TIMESTAMPTZ(3) NOT NULL,
  CONSTRAINT "IdempotencyRecord_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "AuditLog" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "actorId" TEXT NOT NULL,
  "action" TEXT NOT NULL,
  "objectType" TEXT NOT NULL,
  "objectId" TEXT NOT NULL,
  "requestId" TEXT NOT NULL,
  "redactedDiff" JSONB NOT NULL,
  "ipHash" TEXT,
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE TABLE "Outcome" (
  "organizationId" UUID NOT NULL,
  "id" UUID NOT NULL,
  "leadId" UUID NOT NULL,
  "recommendationId" UUID,
  "evidenceEventId" UUID NOT NULL,
  "type" "OutcomeType" NOT NULL,
  "externalMilestoneId" TEXT NOT NULL,
  "operationType" "OperationType" NOT NULL,
  "amount" DECIMAL(14,2),
  "commission" DECIMAL(14,2),
  "occurredAt" TIMESTAMPTZ(3) NOT NULL,
  "recordedBy" UUID NOT NULL,
  "note" VARCHAR(1000),
  "createdAt" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Outcome_pkey" PRIMARY KEY ("organizationId","id")
);

CREATE UNIQUE INDEX "User_authSubject_key" ON "User" ("authSubject");

CREATE UNIQUE INDEX "User_email_key" ON "User" ("email");

CREATE UNIQUE INDEX "Membership_organizationId_userId_key" ON "Membership" ("organizationId","userId");

CREATE UNIQUE INDEX "Broker_organizationId_membershipId_key" ON "Broker" ("organizationId","membershipId");

CREATE UNIQUE INDEX "PolicyVersion_organizationId_version_key" ON "PolicyVersion" ("organizationId","version");

CREATE UNIQUE INDEX "Lead_organizationId_source_externalId_key" ON "Lead" ("organizationId","source","externalId");

CREATE INDEX "Lead_organizationId_brokerId_currentState_idx" ON "Lead" ("organizationId","brokerId","currentState");

CREATE INDEX "Lead_organizationId_queueEligible_rescuePriority_id_idx" ON "Lead" ("organizationId","queueEligible","rescuePriority","id");

CREATE INDEX "Lead_organizationId_nextCheckAt_id_idx" ON "Lead" ("organizationId","nextCheckAt","id");

CREATE INDEX "Lead_organizationId_phone_idx" ON "Lead" ("organizationId","phone");

CREATE INDEX "Lead_organizationId_email_idx" ON "Lead" ("organizationId","email");

CREATE UNIQUE INDEX "LeadEvent_organizationId_source_sourceEventId_key" ON "LeadEvent" ("organizationId","source","sourceEventId");

CREATE INDEX "LeadEvent_organizationId_leadId_occurredAt_receivedAt_id_idx" ON "LeadEvent" ("organizationId","leadId","occurredAt","receivedAt","id");

CREATE INDEX "AnalysisRun_organizationId_leadId_createdAt_idx" ON "AnalysisRun" ("organizationId","leadId","createdAt");

CREATE UNIQUE INDEX "StateHistory_organizationId_analysisRunId_eventId_key" ON "StateHistory" ("organizationId","analysisRunId","eventId");

CREATE UNIQUE INDEX "ScoreSnapshot_organizationId_analysisRunId_leadId_key" ON "ScoreSnapshot" ("organizationId","analysisRunId","leadId");

CREATE INDEX "ScoreSnapshot_organizationId_leadId_calculatedAt_idx" ON "ScoreSnapshot" ("organizationId","leadId","calculatedAt");

CREATE INDEX "Recommendation_organizationId_leadId_status_idx" ON "Recommendation" ("organizationId","leadId","status");

CREATE INDEX "ExceptionCase_organizationId_status_severity_idx" ON "ExceptionCase" ("organizationId","status","severity");

CREATE UNIQUE INDEX "ImportBatch_organizationId_dedupeKey_key" ON "ImportBatch" ("organizationId","dedupeKey");

CREATE UNIQUE INDEX "ImportRow_organizationId_batchId_rowNumber_key" ON "ImportRow" ("organizationId","batchId","rowNumber");

CREATE UNIQUE INDEX "OutboxJob_organizationId_dedupeKey_key" ON "OutboxJob" ("organizationId","dedupeKey");

CREATE INDEX "OutboxJob_organizationId_status_availableAt_idx" ON "OutboxJob" ("organizationId","status","availableAt");

CREATE UNIQUE INDEX "ApiKey_secretHash_key" ON "ApiKey" ("secretHash");

CREATE UNIQUE INDEX "IdempotencyRecord_organizationId_principal_method_path_key_key" ON "IdempotencyRecord" ("organizationId","principal","method","path","key");

CREATE INDEX "AuditLog_organizationId_createdAt_idx" ON "AuditLog" ("organizationId","createdAt");

CREATE UNIQUE INDEX "Outcome_organizationId_evidenceEventId_type_key" ON "Outcome" ("organizationId","evidenceEventId","type");

CREATE UNIQUE INDEX "Outcome_organizationId_leadId_type_externalMilestoneId_key" ON "Outcome" ("organizationId","leadId","type","externalMilestoneId");
