'use client';
import {useRef,useState} from 'react';
import CountryPhonePicker from './country-phone-picker';
import type {CountryCode} from '@/lib/leadrescue/phones';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Table,TableHeader,TableHead,TableBody,TableCell,TableRow} from '@/components/ui/table';
import {detectCsv,readCsv,suggestMapping,validateCsv,errorReport,FIELDS,type Csv,type Mapping,type Field,type RowResult} from '@/lib/leadrescue/csv';
function download(text:string,name:string){const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const sample='nome;email;id_externo;origem;data_criacao\r\nAna Exemplo;ana@example.invalid;demo-1;demonstracao;2026-09-01T12:00:00-03:00\r\nBruno Exemplo;bruno@example.invalid;demo-2;demonstracao;\r\nAna Repetida;ana@example.invalid;demo-3;demonstracao;\r\nContato incompleto;;;;\r\n';
export default function CsvReview(){
  const [csv,setCsv]=useState<Csv|null>(null),[file,setFile]=useState<Blob|null>(null),[filename,setFilename]=useState(''),[mapping,setMapping]=useState<Mapping>({}),[results,setResults]=useState<RowResult[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const version=useRef(0);
  const [country,setCountry]=useState<CountryCode|undefined>();
  async function load(blob:Blob,name:string,delimiter?:','|';'){
    const id=++version.current;setBusy(true);setError('');setResults(null);setCsv(null);
    try{const parsed=await(delimiter?readCsv(blob,delimiter):detectCsv(blob));if(id!==version.current)return;setCsv(parsed);setFile(blob);setFilename(name);setMapping(suggestMapping(parsed.headers));}
    catch(e){if(id===version.current)setError((e as Error).message);}finally{if(id===version.current)setBusy(false);}
  }
  function validate(){setError('');setResults(null);try{if(csv)setResults(validateCsv(csv,mapping,{country}));}catch(e){setError((e as Error).message);}}
  return <main className="max-w-6xl mx-auto p-6 md:p-10 space-y-6">
    <a className="text-primary underline" href="/">Voltar à minha imobiliária</a>
    <div><h1 className="text-3xl font-semibold">Preparar arquivo de leads</h1><p className="mt-3 text-muted-foreground">Confira a identificação dos contatos antes da importação. Esta revisão acontece no navegador e não grava leads no banco.</p></div>
    <section className="bg-card border rounded-xl p-6 space-y-4"><h2 className="text-xl font-semibold">1. Escolha o CSV</h2><label className="block space-y-2"><span>Arquivo UTF-8 · até 20 MiB e 50.000 registros</span><Input type="file" accept=".csv,text/csv" disabled={busy} onChange={e=>{const next=e.target.files?.[0];if(next)void load(next,next.name);}}/></label><div className="flex gap-3 flex-wrap"><Button variant="outline" disabled={busy} onClick={()=>void load(new Blob([sample]),'Exemplo fictício')}>Testar com dados fictícios</Button><Button variant="ghost" onClick={()=>download(sample,'leadrescue-exemplo-ficticio.csv')}>Baixar exemplo</Button></div></section>
    <CountryPhonePicker value={country} onChange={next=>{setCountry(next);setResults(null);}}/>
    {busy&&<p role="status">Lendo arquivo…</p>}{error&&<p role="alert" className="text-destructive border rounded-lg p-4">{error}</p>}
    {results&&<section className="bg-card border rounded-xl p-6 space-y-3"><h2 className="text-xl font-semibold">Telefones normalizados</h2><p>{results.reduce((n,r)=>n+r.phones.filter(p=>p.number).length,0)} números válidos · {results.filter(r=>r.phones.length>1).length} registros com múltiplos telefones.</p><Table><TableHeader><TableRow><TableHead>Registro</TableHead><TableHead>Original</TableHead><TableHead>Formato internacional ou pendência</TableHead></TableRow></TableHeader><TableBody>{results.flatMap(r=>r.phones.map((p,i)=>({p,id:r.row+'-'+i,row:r.row}))).slice(0,20).map(({p,id,row})=><TableRow key={id}><TableCell>{row}</TableCell><TableCell>{p.original}</TableCell><TableCell>{p.error??`${p.number}${p.extension?' ramal '+p.extension:''}`}</TableCell></TableRow>)}</TableBody></Table><p className="text-sm">Prévia de 20 números; o relatório inclui originais, números normalizados e pendências de todos os registros.</p></section>}
    {csv&&<><section className="bg-card border rounded-xl p-6 space-y-5"><h2 className="text-xl font-semibold">2. Confira as colunas</h2><p>{filename} · {csv.rows.length} registros</p><label className="block max-w-xs space-y-2"><span>Separador</span><Select value={csv.delimiter} onValueChange={value=>{if(file)void load(file,filename,value as ','|';');}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value=";">Ponto e vírgula</SelectItem><SelectItem value=",">Vírgula</SelectItem></SelectContent></Select></label><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{(Object.keys(FIELDS) as Field[]).map(field=><label key={field} className="space-y-2"><span>{FIELDS[field]}</span><Select value={mapping[field]===undefined?'none':String(mapping[field])} onValueChange={value=>{setMapping(old=>{const next={...old};if(value==='none')delete next[field];else next[field]=Number(value);return next;});setResults(null);}}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Não informado</SelectItem>{csv.headers.map((header,index)=><SelectItem key={index} value={String(index)}>{index+1}. {header||'Sem título'}</SelectItem>)}</SelectContent></Select></label>)}</div><p className="text-sm text-muted-foreground">Esta primeira revisão cobre identificação e data original em ISO com horário e fuso. As demais colunas não são interpretadas. Números locais usam o país escolhido; inclua o DDD quando necessário.</p><Button onClick={validate}>Validar todos os registros</Button></section>
    <section className="bg-card border rounded-xl overflow-hidden"><h2 className="text-lg font-semibold p-5">Prévia — primeiros 20 registros</h2><Table><TableHeader><TableRow>{csv.headers.map((header,i)=><TableHead key={i}>{header||`Coluna ${i+1}`}</TableHead>)}</TableRow></TableHeader><TableBody>{csv.rows.slice(0,20).map((row,i)=><TableRow key={i}>{row.map((cell,j)=><TableCell key={j}><span className="block max-w-xs truncate" title={cell}>{cell}</span></TableCell>)}</TableRow>)}</TableBody></Table></section></>}
    {results&&<section className="bg-card border rounded-xl p-6 space-y-5"><h2 className="text-xl font-semibold">3. Resultado da revisão</h2><div className="grid sm:grid-cols-3 gap-4">{[['Sem erros de identificação',results.filter(r=>!r.errors.length).length],['Com erros',results.filter(r=>r.errors.length).length],['Possíveis duplicidades no arquivo',results.filter(r=>r.duplicate).length]].map(([label,count])=><div key={label} className="bg-background p-4 rounded-lg"><p className="text-3xl font-semibold">{count}</p><p>{label}</p></div>)}</div><p>Duplicidades são avisos para revisão. Ainda não há comparação com leads do banco nem gravação de registros. A confirmação da importação será disponibilizada na etapa seguinte.</p><Button variant="outline" onClick={()=>download(errorReport(results),'leadrescue-revisao.csv')}>Baixar revisão com telefones normalizados</Button><Table><TableHeader><TableRow><TableHead>Registro</TableHead><TableHead>Identificação</TableHead><TableHead>Erros e avisos</TableHead></TableRow></TableHeader><TableBody>{results.filter(r=>r.errors.length||r.warnings.length).slice(0,100).map(r=><TableRow key={r.row}><TableCell>{r.row}</TableCell><TableCell>{r.name}</TableCell><TableCell>{[...r.errors,...r.warnings].join(' ')}</TableCell></TableRow>)}</TableBody></Table><p className="text-sm text-muted-foreground">Até 100 registros com apontamentos nesta tela; o relatório inclui todos.</p></section>}
  </main>;
}
