"use client";

import { useEffect, useMemo, useState, type CSSProperties } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, Blocks, Check, CircleHelp, Clock3, FlaskConical, LayoutDashboard, ListFilter, LockKeyhole, Radar, Search, ShieldCheck, SlidersHorizontal, Target, Users, X } from 'lucide-react';
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarInset, SidebarTrigger } from '@/components/ui/sidebar';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetClose } from '@/components/ui/sheet';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Progress } from '@/components/ui/progress';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { actionLabels, bandLabels, demoCases, flagLabels, suppressionLabels, type DemoCase } from '@/lib/leadrescue/demo';
import { csvCell, transitionReview, type Review, type ReviewStatus } from '@/lib/leadrescue/engine';

const number=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:2,minimumFractionDigits:2});
const reviewLabels:Record<ReviewStatus,string>={PENDING:'Pendente',ACCEPTED:'Aceita',EXECUTED:'Execução simulada',DISMISSED:'Dispensada'};
const nav=[{id:'overview',label:'Visão geral',icon:LayoutDashboard},{id:'cases',label:'Cenários de leads',icon:Users},{id:'radar',label:'Radar de prioridade',icon:Radar},{id:'roadmap',label:'Etapas do MVP',icon:Blocks}];
const scoreNames=[['LS','Potencial'],['RR','Risco'],['PS','Progressão'],['RP','Prioridade']] as const;

export default function Workspace(){
  const [view,setView]=useState('overview');
  const [tab,setTab]=useState('queue');
  const [query,setQuery]=useState('');
  const [band,setBand]=useState('all');
  const [selected,setSelected]=useState<DemoCase|null>(null);
  const [reviews,setReviews]=useState<Record<string,Review>>({});
  const [note,setNote]=useState('');
  const [help,setHelp]=useState(false);
  const ordered=useMemo(()=>[...demoCases].sort((a,b)=>b.analysis.RP-a.analysis.RP),[]);
  const queue=ordered.filter(c=>c.analysis.queueEligible);
  const hidden=ordered.filter(c=>!c.analysis.queueEligible);
  const critical=queue.filter(c=>c.analysis.priority==='CRITICAL').length;
  const high=queue.filter(c=>c.analysis.priority==='HIGH').length;
  const base=view==='cases'?ordered:tab==='queue'?queue:tab==='suppressed'?hidden:ordered;
  const rows=base.filter(c=>(band==='all'||c.analysis.priority===band)&&(`${c.name} ${c.code} ${c.stage}`.toLowerCase().includes(query.toLowerCase())));
  const selectedReview=selected?(reviews[selected.id]||{status:'PENDING' as const}):undefined;
  const openCase=(c:DemoCase)=>{setNote('');setSelected(c);};
  const navigate=(id:string)=>{setView(id);setQuery('');setBand('all');};
  function changeReview(next:ReviewStatus){
    if(!selected||!selectedReview)return;
    try{
      const updated=transitionReview(selectedReview,next,selected.analysis.queueEligible,note);
      setReviews(previous=>({...previous,[selected.id]:updated}));
      setNote('');toast.success(next==='ACCEPTED'?'Aceitação simulada. Nenhuma ação foi executada.':next==='EXECUTED'?'Registro simulado nesta sessão. Nenhuma mensagem enviada.':'Cenário dispensado nesta sessão.');
    }catch {toast.error('Informe uma justificativa de pelo menos 8 caracteres e respeite a ordem de revisão.');}
  }
  function exportCsv(){
    const data=[['Tipo','Cenário','Nome','LS','RR','PS','RP','Faixa','Na fila','Motivo de supressão','Estado da revisão'],...rows.map(c=>['SINTÉTICO',c.code,c.name,c.analysis.LS,c.analysis.RR,c.analysis.PS,c.analysis.RP,bandLabels[c.analysis.priority],c.analysis.queueEligible?'Sim':'Não',suppressionLabels[c.analysis.suppressionReason||'']||'',reviews[c.id]?reviewLabels[reviews[c.id].status]:'Não revisado'])];
    const blob=new Blob(['\uFEFF'+data.map(row=>row.map(csvCell).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8;'});
    const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='LeadRescue-cenarios-sinteticos.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
    toast.success('Exportação dos cenários exibidos. Dados de demonstração.');
  }
  useEffect(()=>{
    const browser=document as Document & {modelContext?:{registerTool:(t:unknown,options:{signal:AbortSignal})=>void|Promise<void>}};
    if(!browser.modelContext?.registerTool)return;
    const lifecycle=new AbortController();
    const tools=[{name:'list_leadrescue_scenarios',description:'Listar os dez cenários SINTÉTICOS da demonstração LeadRescue e seus scores. Não são leads reais.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>({content:[{type:'text',text:JSON.stringify(demoCases.map(c=>({id:c.id,name:c.name,...c.analysis})))}]})},{name:'open_leadrescue_scenario',description:'Abrir um cenário sintético para inspeção. Não aceita nem executa recomendações.',inputSchema:{type:'object',properties:{scenario_id:{type:'string'}},required:['scenario_id'],additionalProperties:false},execute:async(args:{scenario_id:string})=>{const c=demoCases.find(c=>c.id===args.scenario_id);if(!c)throw new Error('Cenário não encontrado');setSelected(c);setNote('');return {content:[{type:'text',text:'Cenário sintético aberto: '+c.name}]};}}];
    tools.forEach(t=>{try{void Promise.resolve(browser.modelContext?.registerTool({...t,annotations:{readOnlyHint:t.name.startsWith('list_'),untrustedContentHint:false}},{signal:lifecycle.signal})).catch(()=>{});}catch{}});return()=>lifecycle.abort();
  },[]);

  return <SidebarProvider style={{'--sidebar-width':'14.5rem'} as CSSProperties}>
    <Sidebar className="lr-sidebar" collapsible="offcanvas">
      <SidebarHeader className="brand"><div className="brand-icon"><Activity size={25}/></div><div>Lead<span>Rescue</span><small>OPERAÇÃO IMOBILIÁRIA</small></div></SidebarHeader>
      <SidebarContent><SidebarGroup><SidebarGroupLabel className="nav-caption">WORKSPACE</SidebarGroupLabel><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>navigate(n.id)} className="nav-item"><n.icon/><span>{n.label}</span>{n.id==='cases'&&<span className="nav-count">10</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup>
      <div className="sidebar-note"><FlaskConical size={22}/><strong>Ambiente de demonstração</strong><p>Explore as regras com cenários fictícios, sem entrar em contato com clientes.</p><span>Etapa inicial · v0.1</span></div></SidebarContent>
      <SidebarFooter className="sidebar-bottom"><ShieldCheck size={19}/><span>Supervisão humana<br/><small>Envio automático desativado</small></span></SidebarFooter>
    </Sidebar>
    <SidebarInset className="workspace">
      <header className="topbar"><div className="topbar-left"><SidebarTrigger aria-label="Alternar navegação"/><span className="divider"/><span>Imobiliária demonstração</span><span className="demo-tag">DADOS FICTÍCIOS</span></div><Button variant="ghost" size="icon" aria-label="Sobre esta demonstração" onClick={()=>setHelp(true)}><CircleHelp size={20}/></Button></header>
      <main className="content">
        <div className="page-heading"><div><p className="eyebrow">{view==='roadmap'?'DESENVOLVIMENTO DO PRODUTO':'INTELIGÊNCIA DE OPERAÇÃO'}</p><h1>{view==='overview'?'Visão geral':view==='cases'?'Cenários de leads':view==='radar'?'Radar de prioridade':'Etapas do MVP'}</h1><p>{view==='roadmap'?'O que já pode ser experimentado e o que falta para o piloto.':'Identifique o que merece atenção. Entenda o motivo. Decida a próxima ação.'}</p></div>{view!=='roadmap'&&view!=='radar'&&<Button variant="outline" onClick={exportCsv} className="export-btn"><ArrowDownToLine size={17}/>Exportar cenários</Button>}</div>
        <div className="demo-banner"><FlaskConical size={19}/><p><strong>Simulação, não operação real.</strong> Dez testes numéricos do documento-base. As revisões duram apenas nesta sessão; recarregar restaura os cenários.</p></div>

        {view==='roadmap'?<Roadmap/>:<>
          <section className="metrics" aria-label="Indicadores dos cenários"><Metric title="Cenários analisados" value={demoCases.length} detail="Base de testes · Apêndice E" icon={<Users/>}/><Metric title="Prioridade crítica" value={critical} detail="Somente elegíveis para revisão" tone="critical" icon={<Target/>}/><Metric title="Prioridade alta" value={high} detail="Categoria separada dos críticos" tone="high" icon={<Clock3/>}/><Metric title="Fora da fila" value={hidden.length} detail="Bloqueio, dados ou ausência de atraso" icon={<ShieldCheck/>}/></section>

          {view==='radar'?<section className="panel radar-panel"><div className="section-heading"><div><h2>Potencial × risco</h2><p>Um potencial alto, sozinho, não coloca o cenário na fila.</p></div><span className="small-label">LS / RR · cortes em 60</span></div><div className="radar-layout"><div className="radar-outer"><span className="axis-y">Risco de resgate (RR)</span><div className="radar-plot"><div className="cut-v"/><div className="cut-h"/><span className="quadrant q1">Revisar contexto</span><span className="quadrant q2">Atenção prioritária</span><span className="quadrant q3">Acompanhar</span><span className="quadrant q4">Preservar progressão</span>{ordered.map(c=><button className={`radar-dot ${c.analysis.queueEligible?'eligible':'muted-dot'}`} key={c.id} style={{left:`${c.analysis.LS}%`,bottom:`${c.analysis.RR}%`}} onClick={()=>openCase(c)} aria-label={`${c.code} ${c.name}, potencial ${c.analysis.LS}, risco ${c.analysis.RR}`}>{c.code}</button>)}</div><span className="axis-x">Potencial do lead (LS) →</span></div><div className="radar-list"><h3>Todos os pontos</h3><p className="muted">Selecione para ver o cálculo.</p>{ordered.map(c=><button key={c.id} onClick={()=>openCase(c)}><span className="mono">{c.code}</span><span>{c.name}</span><strong>{c.analysis.LS}/{c.analysis.RR}</strong></button>)}</div></div></section>:
          <div className={view==='overview'?'overview-grid':'full-grid'}><section className="panel case-panel"><div className="section-heading"><div><div className="heading-line"><h2>{view==='cases'?'Todos os cenários':'Fila de revisão'}</h2><span className="count-tag">{view==='cases'?10:queue.length}</span></div><p>Ordenação pela prioridade calculada, do maior para o menor.</p></div><ListFilter size={20} className="muted"/></div>
            {view==='overview'&&<Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="case-tabs"><TabsTrigger value="queue">Na fila <span>{queue.length}</span></TabsTrigger><TabsTrigger value="suppressed">Fora da fila <span>{hidden.length}</span></TabsTrigger><TabsTrigger value="all">Todos</TabsTrigger></TabsList></Tabs>}
            <div className="filters"><div className="search-box"><Search size={17}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cenário ou estágio…" aria-label="Buscar cenário"/></div><Select value={band} onValueChange={setBand}><SelectTrigger className="band-select" aria-label="Filtrar prioridade"><SlidersHorizontal size={16}/><SelectValue placeholder="Todas as prioridades"/></SelectTrigger><SelectContent><SelectItem value="all">Todas as prioridades</SelectItem>{Object.entries(bandLabels).map(([k,v])=><SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div>
            <Table className="case-table"><TableHeader><TableRow><TableHead>Cenário / estágio</TableHead><TableHead>Prioridade</TableHead><TableHead className="score-column">LS / RR / PS</TableHead><TableHead>Próxima ação</TableHead><TableHead><span className="sr-only">Abrir</span></TableHead></TableRow></TableHeader><TableBody>{rows.map(c=><TableRow key={c.id}><TableCell><button onClick={()=>openCase(c)} className="case-name"><span className="case-code">{c.code}</span><span><strong>{c.name}</strong><small>{c.stage}</small></span></button></TableCell><TableCell><div className="priority-cell"><strong>{number(c.analysis.RP)}</strong><span className={'badge '+c.analysis.priority.toLowerCase()}>{bandLabels[c.analysis.priority]}</span></div></TableCell><TableCell className="score-column"><div className="inline-scores"><span>{c.analysis.LS}</span><span>{c.analysis.RR}</span><span>{c.analysis.PS}</span></div></TableCell><TableCell><span className="next-action">{c.analysis.queueEligible?actionLabels[c.analysis.action]:suppressionLabels[c.analysis.suppressionReason||'']}</span><small className="subline">{reviews[c.id]?reviewLabels[reviews[c.id].status]:c.analysis.queueEligible?'Revisão humana · '+c.analysis.level:'Não abordar'}</small></TableCell><TableCell><Button variant="ghost" size="icon" onClick={()=>openCase(c)} aria-label={'Abrir '+c.name}><ArrowRight size={17}/></Button></TableCell></TableRow>)}</TableBody></Table>
            {!rows.length&&<div className="empty-state"><Search/><h3>Nenhum cenário encontrado</h3><p>Altere a busca ou limpe o filtro de prioridade.</p><Button variant="outline" onClick={()=>{setQuery('');setBand('all');}}>Limpar filtros</Button></div>}
            <div className="table-footer"><span>{rows.length} de {base.length} cenários</span><span>Scores ≠ probabilidade de compra</span></div></section>
          {view==='overview'&&<aside className="insights"><section className="attention-card"><div className="attention-icon"><ShieldCheck size={24}/></div><p className="eyebrow">PRIMEIRO, AS PROTEÇÕES</p><h2>Prioridade não é permissão para contato.</h2><p>Bloqueios e compromissos futuros são respeitados antes de qualquer recomendação.</p><button onClick={()=>{setTab('suppressed');setQuery('');setBand('all');}}>Ver cenários fora da fila <ArrowRight size={16}/></button></section><section className="panel coverage-card"><h3>Qualidade da evidência</h3><div className="coverage-number">9 <span>/ 10 cenários</span></div><Progress value={90} aria-label="9 de 10 cenários com contexto completo de demonstração"/><p>Contexto completo definido para a simulação. Não mede a cobertura de um CRM real.</p><button className="text-link" onClick={()=>openCase(demoCases[0])}>Revisar o caso incompleto <ArrowRight size={15}/></button></section><div className="clock-note"><Clock3 size={17}/><span>Referência dos testes<br/><strong>10 set. 2026 · 12:00 (São Paulo)</strong></span></div></aside>}
          </div>}
          <div className="bottom-note"><LockKeyhole size={16}/><span>Sem IA generativa, CRM conectado ou envio de mensagens. Aceitar uma recomendação não executa uma ação.</span></div>
        </>}
      </main>
    </SidebarInset>
    <Sheet open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className="detail-sheet" showCloseButton={false}>{selected&&<><SheetHeader><div className="detail-top"><span className="eyebrow">CENÁRIO SINTÉTICO · {selected.code}</span><SheetClose asChild><Button size="icon" variant="ghost" aria-label="Fechar detalhe"><X size={20}/></Button></SheetClose></div><SheetTitle>{selected.name}</SheetTitle><SheetDescription>{selected.summary}</SheetDescription></SheetHeader><div className="detail-body"><div className="detail-labels"><span className="badge neutral">{selected.stage}</span><span className="badge neutral">{selected.owner}</span></div>
      {!selected.analysis.queueEligible&&<div className="gate-banner"><ShieldCheck size={21}/><div><strong>{suppressionLabels[selected.analysis.suppressionReason||'']}</strong><p>Fora da fila comercial. A prioridade bruta continua visível para explicar o diagnóstico.</p></div></div>}
      <div className="score-grid">{scoreNames.map(([key,label])=><div key={key}><span>{key} · {label}</span><strong>{key==='RP'?number(selected.analysis[key]):selected.analysis[key]}</strong></div>)}</div>
      <section className="detail-section"><h3>Cálculo explicável</h3><div className="formula">0,45 × {selected.analysis.LS} + 0,35 × {selected.analysis.RR} + 0,20 × (100 − {selected.analysis.PS}) = <strong>{number(selected.analysis.RP)}</strong></div><p className="muted">Fonte: Apêndice E → {selected.id}. Componentes de teste; não são eventos de uma conversa.</p><h4>Potencial (LS)</h4><div className="component-list">{['Prazo','Capacidade financeira','Engajamento','Compatibilidade','Comportamento comercial'].map((label,i)=><div key={label}><span>{label}</span><strong>+{selected.input.leadComponents[i]}</strong></div>)}</div><h4>Risco (RR)</h4><div className="component-list">{selected.analysis.riskComponents.length?selected.analysis.riskComponents.map(r=><div key={r.code}><span>{flagLabels[r.code]}</span><strong>{r.points>0?'+':''}{r.points}</strong></div>):<p className="muted">Nenhum fator de risco informado.</p>}{selected.input.zeroRiskGate&&<div className="gate-line"><span>Proteção aplicada</span><strong>RR = 0</strong></div>}</div><h4>Progressão (PS)</h4><div className="formula small-formula">Q {selected.input.progression.Q} + T {selected.input.progression.T} + V {selected.input.progression.V} + C {selected.input.progression.C} + P {selected.input.progression.P} + N {selected.input.progression.N} − S {selected.input.progression.S} − R {selected.input.progression.R} − A {selected.input.progression.A}</div><p className="muted">Qualificação + avanço + visitas + propostas + próxima ação − estagnação − repetição − ausência de próxima ação. Limitado a 0–100.</p></section>
      <section className="review-section"><div className="heading-line"><h3>{selected.analysis.queueEligible?'Simular revisão humana':'Orientação interna'}</h3><span className="badge neutral">{selected.analysis.level}</span></div><p>{actionLabels[selected.analysis.action]}</p>{selected.analysis.queueEligible?<><div className="review-status"><span>Estado da simulação</span><strong>{reviewLabels[selectedReview!.status]}</strong></div>{selectedReview?.status==='PENDING'&&<Button className="primary-button" onClick={()=>changeReview('ACCEPTED')}><Check size={17}/>Simular aceitação</Button>}{(selectedReview?.status==='PENDING'||selectedReview?.status==='ACCEPTED')&&<><label htmlFor="evidence">{selectedReview.status==='ACCEPTED'?'Evidência fictícia da ação externa':'Motivo para dispensar (opcional até dispensar)'}</label><Textarea id="evidence" value={note} onChange={e=>setNote(e.target.value)} maxLength={1200} placeholder="Use apenas texto fictício. Não inclua informações de clientes."/><div className="review-buttons">{selectedReview.status==='ACCEPTED'&&<Button className="primary-button" disabled={note.trim().length<8} onClick={()=>changeReview('EXECUTED')}>Simular registro de execução</Button>}<Button variant="outline" disabled={note.trim().length<8} onClick={()=>changeReview('DISMISSED')}>Dispensar cenário</Button></div></>}{selectedReview?.note&&<div className="saved-note"><strong>Registro desta sessão</strong><p>{selectedReview.note}</p></div>}<p className="muted">Nenhuma mensagem será enviada e nenhuma venda será atribuída. Os scores do teste permanecem fixos. Esta revisão desaparece ao recarregar a página.</p></>:<p className="muted">Este cenário não permite simular uma ação comercial. {selected.analysis.suppressionReason==='LOW_COVERAGE'?'Revisar os dados é o próximo passo; não há prova de abandono.':'Aguardar ou respeitar a proteção vigente.'}</p>}</section>
      </div></>}</SheetContent></Sheet>
    <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogHeader><DialogTitle>O que esta versão demonstra</DialogTitle><DialogDescription>Primeira entrega de validação, baseada no LeadRescue MVP Build Specification v0.1.0.</DialogDescription></DialogHeader><div className="help-body"><p>Os dez cenários são testes de componentes. Alguns combinam fatores apenas para testar limites; não representam conversas reais.</p><p>A tela demonstra scores, proteções, priorização e revisão humana. Não existe banco comercial, login por imobiliária, importação real ou integração de atendimento.</p><p>Dados e notas não são enviados a servidores pela demonstração. Revisões ficam somente na memória da página. Não insira dados pessoais.</p><Button onClick={()=>{setHelp(false);navigate('roadmap');}}>Ver etapas do MVP</Button></div></DialogContent></Dialog>
    <Toaster richColors position="bottom-right"/>
  </SidebarProvider>;
}

function Metric({title,value,detail,icon,tone='neutral'}:{title:string;value:number;detail:string;icon:React.ReactNode;tone?:string}){return <article className={'metric metric-'+tone}><div className="metric-top"><span>{title}</span>{icon}</div><strong>{String(value).padStart(2,'0')}</strong><p>{detail}</p></article>;}

function Roadmap(){
  const stages=[['0','Fundação','Em andamento','Contratos extraídos e demonstração criada. Faltam PostgreSQL, migrations executadas, autenticação e testes reais de isolamento.'],['1','Eventos e API','Pendente','Ingestão autenticada, idempotência, replay de eventos, outbox e autorização por organização.'],['2','Importação CSV','Pendente','Upload privado, mapeamento, validação por linha, reimportação e relatório de qualidade.'],['3','Regras e calendário','Parcial','Cálculos de componentes implementados. Extração a partir de eventos, SLA, scheduler e concorrência ainda pendentes.'],['4','Revisão e exceções','Simulação','Aceitação e registro simulados na sessão. Persistência, permissões e auditoria no servidor ainda pendentes.'],['5','Resultados e IA opcional','Pendente','Auditoria histórica, resultados com evidência e testes da IA opcional. Sem atribuição causal de receita.'],['6','Preparação do piloto','Pendente','Segurança, restauração de backup, privacidade, carga, testes ponta a ponta e aceite com imobiliária.']];
  return <><section className="panel roadmap"><div className="section-heading"><div><h2>Da especificação ao piloto</h2><p>A interface pronta não encerra uma etapa técnica.</p></div><span className="badge high">Piloto ainda não liberado</span></div>{stages.map(([n,title,status,description])=><div className="roadmap-row" key={n}><span className={'sprint-number '+(n==='0'?'active':'')}>{n}</span><div><h3>{title}</h3><p>{description}</p></div><span className={'badge '+(status==='Pendente'?'neutral':'medium')}>{status}</span></div>)}</section><section className="next-delivery"><Blocks size={26}/><div><h3>Próxima entrega: fundação segura</h3><p>Conectar um PostgreSQL de testes e a autenticação, aplicar as migrations e provar que uma imobiliária não consegue acessar dados de outra. Usar apenas dados sintéticos até concluir essas verificações.</p></div></section></>;
}
